apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sre-api-ingress
  namespace: sre-platform
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sre-api
                port:
                  number: 80